USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION s3_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::891982901397:role/SnowflakeS3Role'
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = (
    's3://modern-retail-lakehouse-lucky/published/'
);

DESC STORAGE INTEGRATION s3_int;