USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MODERN_LAKEHOUSE;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE CUSTOMER_ANALYTICS (
 CUSTOMER_ID STRING,
 CUSTOMER_CITY STRING,
 CUSTOMER_STATE STRING,

 TOTAL_ORDERS NUMBER,
 TOTAL_SPENT FLOAT,
 AVERAGE_SPENT FLOAT,

 FIRST_ORDER TIMESTAMP,
 LAST_ORDER TIMESTAMP
);

CREATE OR REPLACE TABLE PRODUCT_ANALYTICS (
 PRODUCT_ID STRING,
 PRODUCT_CATEGORY_NAME STRING,

 UNITS_SOLD NUMBER,
 TOTAL_REVENUE FLOAT,

 TOTAL_REVIEWS NUMBER,
 AVG_RATING FLOAT
);

CREATE OR REPLACE TABLE SELLER_ANALYTICS (

    SELLER_ID STRING,
    SELLER_CITY STRING,
    SELLER_STATE STRING,

    TOTAL_ORDERS NUMBER,
    TOTAL_PRODUCTS_SOLD NUMBER,
    TOTAL_REVENUE FLOAT,
    AVERAGE_ORDER_VALUE FLOAT

);

CREATE OR REPLACE TABLE SALES_ANALYTICS (

    ORDER_DATE DATE,

    TOTAL_ORDERS NUMBER,
    TOTAL_CUSTOMERS NUMBER,

    TOTAL_REVENUE FLOAT,
    AVERAGE_ORDER_VALUE FLOAT

);

CREATE OR REPLACE TABLE CLV_ANALYTICS (

    CUSTOMER_ID STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING,

    TOTAL_ORDERS NUMBER,
    LIFETIME_VALUE FLOAT,
    AVERAGE_ORDER_VALUE FLOAT,

    FIRST_PURCHASE TIMESTAMP,
    LAST_PURCHASE TIMESTAMP,

    CUSTOMER_SEGMENT STRING

);

LIST @published_stage;